changes to control DRBD server running in usermode
The module parameters and /proc nodes for the usermode SCST/DRBD server
appear in a fuse filesystem mounted by default on /UMCfuse, overridable
by setting $UMC_FS_ROOT in the server's environment.

In addition, /UMCfuse/dev contains a node for each block device
registered in the UMC (usermode compatibility) environment.  That would
include replicated devices exported by DRBD, and the TCMU backing
devices it consumes.

A single set of binary utilities controls either a usermode server or a
kernel-based server, determined at runtime by existence (or not) of
environment variable $UMC_FS_ROOT.

To control a usermode server, the utility programs and scripts must have
set environment UMC_FS_ROOT=/UMCfuse.  The server must also run with
$UMC_FS_ROOT set, because the DRBD server invokes its own utilities
through "usermode helpers", and they inherit the environment of the
server.  All components must run with the same setting for $UMC_FS_ROOT.

Utility/script behavior if environment variable $UMC_FS_ROOT is defined:
...prepend $UMC_FS_ROOT to /proc and /dev pathname lookups
...do not check that DRBD module is modloaded
...omit STAT_CHECKS of /UMCfuse/dev/drbd* (looking like regular files)
...omit MODPROBE of drbd that otherwise occurs if not seen in /proc
...Use IPv4 sockets instead of netlink, peer at 127.0.0.1:1234 (XXX)
...omit ENABLE_NETLINK_MULTICAST because it is not yet supported

diff --git a/scripts/drbddisk b/scripts/drbddisk
--- a/scripts/drbddisk
+++ b/scripts/drbddisk
@@ -7,6 +7,8 @@
 #
 ###
 
+PROC_DRBD=$UMC_FS_ROOT/proc/drbd
+
 DEFAULTFILE="/etc/default/drbd"
 DRBDADM="/sbin/drbdadm"
 
@@ -35,7 +37,7 @@ fi
 drbd_set_role_from_proc_drbd()
 {
 	local out
-	if ! test -e /proc/drbd; then
+	if ! test -e $PROC_DRBD; then
 		ROLE="Unconfigured"
 		return
 	fi
@@ -51,7 +53,7 @@ drbd_set_role_from_proc_drbd()
 		return
 	fi
 
-	if out=$(sed -ne "/^ *$minor: cs:/ { s/:/ /g; p; q; }" /proc/drbd); then
+	if out=$(sed -ne "/^ *$minor: cs:/ { s/:/ /g; p; q; }" $PROC_DRBD); then
 		set -- $out
 		ROLE=${5%/*}
 		: ${ROLE:=Unconfigured} # if it does not show up
@@ -103,7 +105,7 @@ case "$CMD" in
 		# report it as possibly running, so heartbeat can, after failed
 		# stop, do a recovery by reboot.
 		# drbdsetup may fail for obscure reasons, e.g. if /var/lock/ is
-		# suddenly readonly.  So we retry by parsing /proc/drbd.
+		# suddenly readonly.  So we retry by parsing $PROC_DRBD.
 		drbd_set_role_from_proc_drbd
 	esac
 	case $ROLE in
